# Site settings
title: Cyndy Parr home page
email: csparr@gmail.om
description: > # this means to ignore newlines until "baseurl:"
  My personal web page
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: cydparr
github_username:  csparr

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


